var dataSources = [
	"Facebook",
	"Google",
	"Amazon",
	"Twitter",
	"LinkedIn",
	"Instagram",
	"3DStats",
	"51.La",
	"6Sense",
	"99stats",
	"AbandonAid",
	"AccessAnalyzer",
	"AD EBiS",
	"ADARA Analytics",
	"AddFreeStats",
	"Adometry",
	"AdPlan",
	"AgilOne",
	"Akanoo",
	"Alexa Metrics",
	"Alexa Traffic Rank",
	"Alexa Widget",
	"Amplitude",
	"Anametrix",
	"Anormal Tracker",
	"Aplus Analytics",
	"AppDynamics",
	"AT Internet",
	"Autonomy",
	"AVANSER",
	"AWStats",
	"BackType Widgets",
	"Beencounter",
	"BelStat",
	"Beslist",
	"Bluemetrix",
	"Branica",
	"BrightEdge",
	"Browser-Statistik",
	"Bubblestat",
	"Burt",
	"BusinessOnLine Analytics",
	"C3 Metrics",
	"CallRail",
	"Cedexis Radar",
	"Certifica Metric",
	"Channel Intelligence",
	"ChannelAdvisor",
	"ChartBeat",
	"ClearSaleing",
	"ClickInc",
	"ClickMeter",
	"ClickTale",
	"Clicky",
	"ClixMetrix",
	"ClustrMaps",
	"CNZZ",
	"CompeteXL",
	"Conmio",
	"Conversion Logic",
	"ConversionRuler",
	"Coremetrics",
	"CraftKeys",
	"Crazy Egg",
	"crmmetrix",
	"Crowd Science",
	"Dataium",
	"DC StormIQ",
	"Delacon",
	"Demandware Analytics",
	"Deqwas",
	"Didit Blizzard",
	"Didit Maestro",
	"Digital Analytix",
	"DomoDomain",
	"DoubleVerify",
	"Econda",
	"Effective Measure",
	"Ehavior",
	"Eloqua",
	"Encore Metrics",
	"Enecto Analytics",
	"Ensighten",
	"eProof",
	"eStat",
	"etracker",
	"Eulerian",
	"eVisit Analyst",
	"expo-MAX",
	"Extole",
	"eXTReMe Tracker",
	"Fanplayr",
	"Feedjit",
	"Fireclick",
	"Flurry",
	"Fonts.com",
	"Footprint",
	"ForeSee",
	"Free Counter",
	"Free Online Users",
	"G3NESIS",
	"Gaug.es",
	"GB-World",
	"Gemius",
	"Geovisite",
	"Gigya Social Analytics",
	"GoDaddy Site Analytics",
	"GoingUp",
	"Google Analytics",
	"Google Website Optimizer",
	"GoSquared",
	"GoStats",
	"GovMetric",
	"Gravity Insights",
	"GTop",
	"Heap",
	"Heatmap",
	"Histats",
	"Hit-Parade",
	"HitsLink",
	"HitSniffer",
	"HotLog",
	"HubSpot",
	"Hupso",
	"i.ua",
	"IceRocket Tracker",
	"iCrossing",
	"ICStats",
	"InferClick",
	"INFOnline",
	"Innometrics",
	"InsightExpress",
	"Inspectlet",
	"Integral Ad Science",
	"IntelligenceFocus",
	"Intilery",
	"iPerceptions",
	"Jet Interactive",
	"Jirafe",
	"Kameleoon",
	"Keen IO",
	"Kenshoo",
	"KeyMetric",
	"KissInsights",
	"KISSmetrics",
	"Kontagent",
	"LeadFormix",
	"LeadFormix",
	"LeadLander",
	"LeadLife",
	"Leady",
	"LineZing",
	"LinkSmart",
	"LiveBall",
	"Livecounter",
	"LiveInternet",
	"Localytics",
	"LongTail Video Analytics",
	"Lucky Orange",
	"LXR100",
	"Lynchpin Analytics",
	"Lyris ClickTracks",
	"Marketo",
	"Marktest",
	"MdotLabs",
	"Media Innovation Group",
	"Meetrics",
	"MegaIndex",
	"Microsoft Analytics",
	"MineWhat",
	"Mint",
	"Mixpanel",
	"Mobalyzer",
	"Modernus",
	"Mokono Analytics",
	"Monetate",
	"Mongoose Metrics",
	"Monitis",
	"Motigo Webstats",
	"MotionPoint",
	"Mouseflow",
	"MouseStats",
	"Movable Media",
	"MyBlogLog",
	"MyCounter.ua",
	"MyPagerank",
	"MyStat",
	"Nakanohito",
	"Navegg",
	"NDN Analytics",
	"Netminers",
	"NetMonitor",
	"NetRatings SiteCensus",
	"NetUpdater",
	"New Relic",
	"News Registry",
	"NextSTAT",
	"NGDATA",
	"Ninja Access Analysis",
	"Nirror",
	"Nurago",
	"Observer",
	"Ometria",
	"OneStat",
	"Onlinewebstat",
	"Open Web Analytics",
	"Openstat",
	"Opentracker",
	"OrangeSoda",
	"OWA",
	"PercentMobile",
	"Petametrics",
	"Phonalytics",
	"phpMyVisites",
	"Piwik Analytics",
	"Premonix",
	"Proficientz",
	"Pt engine",
	"PublishFlow",
	"QCRI Analytics",
	"Qualtrics",
	"Quartic",
	"RadarURL",
	"Radware",
	"RapidApe",
	"Reactful",
	"Realtime",
	"Reinvigorate",
	"Rich",
	"RUMAnalytics",
	"SageMetrics",
	"Say.ac",
	"Sayyac",
	"Scout Analytics",
	"SearchIgnite",
	"SeeVolution",
	"SeeWhy",
	"Segment.io",
	"Sepyra",
	"SessionCam",
	"ShinyStat",
	"SingleFeed",
	"SiteBro",
	"SiteMeter",
	"SiteTag",
	"SiteWit",
	"SkyGlue",
	"SkyTide Anlaytics",
	"Snoobi",
	"SOASTA mPulse",
	"Sociocast",
	"Sophus3",
	"Spinnakr",
	"Spring Metrics",
	"Stat24",
	"stat4u",
	"Statcounter",
	"Statisfy",
	"statistics.ro",
	"Tealeaf",
	"Tealium",
	"Terren",
	"TNS",
	"TouchCommerce",
	"TrackingSoft",
	"TrackJS",
	"Trackset ConversionLab",
	"Trackset VisualPath",
	"TradeTracker",
	"Trafic",
	"trak.io",
	"trendcounter",
	"Trovus Revelations",
	"TruEffect",
	"Truehits.net",
	"TubeMogul",
	"TwitterCounter",
	"Typepad Stats",
	"Umbel",
	"Unica",
	"Uptrends",
	"Usability Sciences WebIQ",
	"USERcycle",
	"USERDIVE",
	"UserZoom",
	"Velti mGage Visualize",
	"VG Wort",
	"Visible Measures",
	"VisiStat",
	"Visit Streamer",
	"VisitorVille",
	"Visual Revenue",
	"VisualDNA",
	"VisualVisitor",
	"ViviStats",
	"Vizu",
	"Vizzit",
	"W3Counter",
	"w3roi",
	"Web Traxs",
	"Web Wipe Anlaytics",
	"Web-Stat",
	"WebAntenna",
	"WebGozar",
	"WebProspector",
	"webtrack",
	"WebTracker",
	"Webtraffic",
	"Webtrekk",
	"WebVisor",
	"WiredMinds",
	"Woopra",
	"Wordpress Stats",
	"WOW Analytics",
	"WriteUp ClickAnalyzer",
	"WysiStat",
	"XGraph",
	"Yahoo Analytics",
	"Yahoo Search Marketing Analytics",
	"Yahoo! Buzz",
	"Yandex.Metrics",
	"YellowTracker",
	"Yola Analytics"
]